on: [push, pull_request]
name: CI
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@cargo-binstall
      - run: just _install-tools-after-binstall
      - uses: Swatinem/rust-cache@v2
      - run: just lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/install-action@just
      - uses: taiki-e/install-action@cargo-binstall
      - run: just _install-tools-after-binstall
      - uses: Swatinem/rust-cache@v2
      - run: just test
